"""Several dvisvgm SVGs in one document must not share glyph names.

dvisvgm numbers its glyph paths per FILE, so every figure restarts at g0-1.
Inlined into one page, the second figure's `<use xlink:href="#g0-48">` resolves
to the FIRST figure's glyph — the figure still renders, with the wrong letters.

Measured on kolbe2018hubbard before the fix: 9 inline SVGs, 25 ids defined more
than once, 112 of 336 glyph references (33%) pointing into a foreign figure.
Reported by the external drillcheck audit; these tests pin both the transform
and every projector that inlines.
"""
import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from pdfdrill.svg_ids import collect_ids, inline_body, namespace_svg_ids, safe_token

_A = ("<?xml version='1.0'?>\n<!-- generated by dvisvgm -->\n"
      "<svg xmlns='http://www.w3.org/2000/svg'>"
      "<defs><path id='g0-48' d='M0 0h1'/><path id='g0-49' d='M1 1h1'/></defs>"
      "<g id='page1'><use xlink:href='#g0-48' x='0'/>"
      "<use xlink:href='#g0-49' x='9'/></g></svg>")

_REF = re.compile(r"""\b(?:xlink:href|href)\s*=\s*(['"])#([^'"]+)\1""")


def _refs(svg):
    return [m.group(2) for m in _REF.finditer(svg)]


# --------------------------------------------------------------------------
# the transform
# --------------------------------------------------------------------------

def test_every_definition_and_its_references_move_together():
    out = namespace_svg_ids(_A, "T-")
    assert collect_ids(out) == {"T-g0-48", "T-g0-49", "T-page1"}
    assert _refs(out) == ["T-g0-48", "T-g0-49"]


def test_the_edge_set_is_preserved():
    """Same number of definitions and references — renaming, not editing."""
    out = namespace_svg_ids(_A, "T-")
    assert len(collect_ids(out)) == len(collect_ids(_A))
    assert len(_refs(out)) == len(_refs(_A))


def test_geometry_and_text_are_untouched():
    out = namespace_svg_ids(_A, "T-")
    assert "d='M0 0h1'" in out and "d='M1 1h1'" in out and "x='9'" in out


def test_a_dangling_reference_stays_dangling():
    """Prefixing a reference to an id this file does not define would make it
    start resolving to a neighbour's glyph — inventing a link, not fixing one."""
    svg = "<svg><path id='a' d='M0 0'/><use xlink:href='#missing'/></svg>"
    out = namespace_svg_ids(svg, "T-")
    assert "#missing" in out and "#T-missing" not in out


def test_url_references_are_rewritten_too():
    svg = "<svg><clipPath id='c1'><rect/></clipPath><g clip-path='url(#c1)'/></svg>"
    out = namespace_svg_ids(svg, "T-")
    assert "url(#T-c1)" in out and collect_ids(out) == {"T-c1"}


def test_a_bad_token_is_refused_rather_than_producing_broken_ids():
    for bad in ("a b", "a#b", "", None, "a'b"):
        with pytest.raises(ValueError):
            namespace_svg_ids(_A, bad)


def test_safe_token_reduces_an_object_id_and_is_never_empty():
    assert safe_token("obj_7e57cda0ba6b") == "obj_7e57cda0ba6b-"
    assert safe_token("a b/c") == "abc-"
    assert safe_token("") == "x-"
    assert safe_token(None) == "x-"


def test_inline_body_strips_the_prolog_and_can_namespace():
    plain = inline_body(_A)
    assert plain.startswith("<svg") and "<?xml" not in plain and "dvisvgm" not in plain
    assert collect_ids(plain) == {"g0-48", "g0-49", "page1"}
    assert collect_ids(inline_body(_A, "T-")) == {"T-g0-48", "T-g0-49", "T-page1"}


def test_inline_body_on_junk_yields_nothing():
    for junk in ("", None, "no svg here", 42):
        assert inline_body(junk) == ""


# --------------------------------------------------------------------------
# every projector that inlines more than one
# --------------------------------------------------------------------------

def _two_svg_model():
    """Two graphics whose SVGs use IDENTICAL dvisvgm ids — the real shape."""
    return {
        "meta": {"bibkey": "k", "num_pages": 1,
                 "pages": [{"page": 1, "page_width": 100, "page_height": 100}]},
        "streams": {},
        "objects": [
            {"id": "d1", "type": "Diagram", "realizations": [],
             "props": {"page": 1, "svg": _A, "latex_code": "\\begin{tikzpicture}"}},
            {"id": "t1", "type": "Table", "realizations": [],
             "props": {"page": 1, "svg": _A, "latex_code": "\\begin{tabular}"}},
        ],
        "alignments": [],
    }


def test_the_inspector_gives_each_figure_its_own_id_space():
    from pdfdrill import docinspect
    m = _two_svg_model()
    els, _ = docinspect.collect_elements(m, docinspect.build_stream_index(m))
    a = [e for e in els if e["id"] == "d1"][0]["props"]["svg"]
    b = [e for e in els if e["id"] == "t1"][0]["props"]["svg"]
    assert collect_ids(a).isdisjoint(collect_ids(b)), "two figures share ids"
    # and each figure still points at its OWN glyphs
    assert set(_refs(a)) <= collect_ids(a)
    assert set(_refs(b)) <= collect_ids(b)


def test_the_tiddler_projector_gives_each_figure_its_own_id_space():
    import json
    from docops.base import OperatorConfig
    from docops.projectors.tiddlywiki import TiddlyWikiProjector
    from docmodel.core import Document
    doc = Document.from_dict(_two_svg_model())
    tids = json.loads(TiddlyWikiProjector(
        OperatorConfig(op="projector", classname="TiddlyWikiProjector")).project(doc))
    fields = [t["svg_tiddler"] for t in tids if t.get("svg_tiddler")]
    assert len(fields) == 2, fields
    assert collect_ids(fields[0]).isdisjoint(collect_ids(fields[1]))
    for f in fields:
        assert set(_refs(f)) <= collect_ids(f)


def test_the_formula_report_gives_each_figure_its_own_id_space():
    from docops.base import OperatorConfig
    from docops.projectors.formula_report import FormulaReportProjector
    from docmodel.core import Document
    doc = Document.from_dict(_two_svg_model())
    out = FormulaReportProjector(
        OperatorConfig(op="projector", classname="FormulaReportProjector")).project(doc)
    blocks = re.findall(r"<svg\b.*?</svg>", out, re.S)
    assert len(blocks) == 2, f"{len(blocks)} svg blocks"
    assert collect_ids(blocks[0]).isdisjoint(collect_ids(blocks[1]))
