"""A locally rendered SVG beats a MathPix crop — the inspector must show it.

`pdfdrill svg` compiles a Diagram's/Table's `latex_code` through
latex→dvisvgm and stores the result on `props["svg"]`. The TiddlyWiki projector
transcludes that. The inspector did not know the field existed: its figure
renderer went straight to the page bitmap or the CDN crop, so on a document
whose TikZ figures HAD been rendered, the inspector still showed the raster
MathPix image — the sharp vector version sitting unused in the same object.

Pinned here because the two projectors reading the same model must not disagree
about which representation wins.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from pdfdrill import docinspect

_SVG = ("<?xml version='1.0' encoding='UTF-8'?>\n"
        "<!-- This file was generated by dvisvgm 3.0 -->\n"
        "<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'svg11.dtd'>\n"
        "<svg width='120pt' height='60pt'><rect width='10' height='10'/></svg>")


# --------------------------------------------------------------------------
# svg_inline — hand the browser a root <svg>, not an XML document
# --------------------------------------------------------------------------

def test_svg_inline_drops_everything_before_the_root_element():
    """An XML declaration inside innerHTML is not markup the browser renders —
    it lands as literal text above the figure."""
    out = docinspect.svg_inline(_SVG)
    assert out.startswith("<svg")
    assert "<?xml" not in out and "<!DOCTYPE" not in out
    assert "dvisvgm" not in out
    assert out.endswith("</svg>")


def test_svg_inline_leaves_a_bare_svg_alone():
    bare = "<svg viewBox='0 0 1 1'><g/></svg>"
    assert docinspect.svg_inline(bare) == bare


def test_svg_inline_on_junk_yields_nothing_rather_than_broken_markup():
    for junk in ("", None, "not svg at all", "<html><body>oops</body></html>"):
        assert docinspect.svg_inline(junk) == ""


# --------------------------------------------------------------------------
# the element record carries the rendered flag
# --------------------------------------------------------------------------

def _model(objs):
    return {"meta": {"bibkey": "k", "num_pages": 1,
                     "pages": [{"page": 1, "page_width": 100, "page_height": 100}]},
            "streams": {}, "objects": objs, "alignments": []}


def test_a_rendered_diagram_is_marked_as_having_an_svg():
    m = _model([{"id": "d1", "type": "Diagram", "realizations": [], "props": {
        "page": 1, "svg": _SVG, "latex_code": "\\begin{tikzpicture}\\end{tikzpicture}",
        "cdn_url": "https://cdn.mathpix.com/crop.jpg"}}])
    els, _ = docinspect.collect_elements(m, docinspect.build_stream_index(m))
    d = [e for e in els if e["id"] == "d1"][0]
    assert d["has_svg"] is True
    # the SVG itself travels once, in props — not copied to a second key, or a
    # 55-diagram document doubles the size of an already 7 MB file.
    assert d["props"]["svg"].startswith("<svg")
    assert "svg" not in {k for k in d if k == "svg"}


def test_an_unrendered_figure_is_not_marked():
    m = _model([{"id": "p1", "type": "Picture", "realizations": [],
                 "props": {"page": 1, "cdn_url": "https://cdn.mathpix.com/x.jpg"}}])
    els, _ = docinspect.collect_elements(m, docinspect.build_stream_index(m))
    p = [e for e in els if e["id"] == "p1"][0]
    assert not p.get("has_svg")


def test_the_stored_svg_is_normalised_once_at_build_time():
    """Normalising in Python keeps the client simple and means the XML preamble
    is not shipped to every reader in a 7 MB file."""
    m = _model([{"id": "t1", "type": "Table", "realizations": [],
                 "props": {"page": 1, "svg": _SVG, "raw_text": "a b"}}])
    els, _ = docinspect.collect_elements(m, docinspect.build_stream_index(m))
    t = [e for e in els if e["id"] == "t1"][0]
    assert t["has_svg"] is True
    assert t["props"]["svg"].startswith("<svg")
    assert "<?xml" not in t["props"]["svg"]


# --------------------------------------------------------------------------
# the client renders it
# --------------------------------------------------------------------------

def test_the_figure_renderer_prefers_the_svg_over_the_crop():
    m = _model([{"id": "d1", "type": "Diagram", "realizations": [], "props": {
        "page": 1, "svg": _SVG, "cdn_url": "https://cdn.mathpix.com/crop.jpg"}}])
    doc = docinspect.build_inspector_html(m, pages={}, title="k")
    data = json.loads(doc.split("const DATA = ", 1)[1].split(";\n", 1)[0])
    assert data["elements"][0]["has_svg"] is True
    # the renderer must consult it — a payload flag nothing reads is not a fix
    assert "has_svg" in doc
    assert "svgfig" in doc


# --------------------------------------------------------------------------
# run the shipped decision, not a string search for it
# --------------------------------------------------------------------------

def _svg_node_block() -> str:
    tpl = docinspect._TEMPLATE
    i = tpl.index("function svgNode(e){")
    j = tpl.index("\n}", i) + 2
    return tpl[i:j]


def _run_svg_node(element) -> str:
    """Return the class of the node svgNode() produced, or "" for null."""
    import json as _json, shutil, subprocess, textwrap
    import pytest as _pytest
    if shutil.which("node") is None:
        _pytest.skip("node not installed")
    harness = textwrap.dedent("""
        function el(tag, cls){ return {tag: tag, cls: cls || "", innerHTML: ""}; }
        %s
        const n = svgNode(%s);
        console.log(JSON.stringify(n === null ? {} : {cls: n.cls, html: n.innerHTML}));
    """) % (_svg_node_block(), _json.dumps(element))
    p = subprocess.run(["node", "-e", harness], capture_output=True, text=True)
    assert p.returncode == 0, p.stderr
    return _json.loads(p.stdout.strip().splitlines()[-1])


def test_svg_node_builds_the_vector_figure_for_a_rendered_element():
    got = _run_svg_node({"has_svg": True, "props": {"svg": "<svg><g/></svg>"},
                         "cdn_url": "https://cdn.mathpix.com/x.jpg"})
    assert got.get("cls") == "svgfig"
    assert got.get("html") == "<svg><g/></svg>"


def test_svg_node_declines_when_there_is_nothing_rendered():
    assert _run_svg_node({"cdn_url": "https://cdn.mathpix.com/x.jpg"}) == {}
    assert _run_svg_node({"has_svg": True, "props": {}}) == {}
