"""831 — a document's README: what it is, where it came from, what was done to it.

A drilled folder holds up to forty files and says nothing about itself. Which
route produced the model, whether a paid conversion is in there, what has been
run and what has deliberately not — all of it is recorded, in the sidecar, and
readable only by someone who knows the sidecar's shape.

This projects that record. It DERIVES NOTHING: every value comes from the
sidecar (`facts`, `evidence`, `pdfinfo`, `transitions`), from the model's own
build stamp, or from `commands.yaml`. A second collector would be a second
opinion, and the point of a provenance file is that there is only one.

The shape is the SKILL convention — YAML front matter for a machine, Markdown
below it for a reader — so `pdfdrill readme --json` and a person opening the
folder get the same answer.

TWO THINGS IT MUST SAY, and they are the reason it exists:

  * WHAT WAS PAID FOR. `mathpix`, `translate`, `vision`, `bibfetch`, `snip`,
    `refine` and `lean` cost money or leave the machine. A folder that contains
    a MathPix conversion is worth more than the PDF it came from and cannot be
    rebuilt for free; nothing in the folder currently says so.
  * WHAT HAS NOT BEEN RUN. A property that is not established is ABSENT, not
    false. Listing only what happened turns "never attempted" into "nothing
    there", which is how `code` got called "dropped entirely" when 97.5% of it
    was already recovered.
"""
from __future__ import annotations

import datetime
import json
from pathlib import Path

#: Written at the top of the file, because it will be.
_HEADER = ("<!-- generated by `pdfdrill readme` — do not hand-edit; "
           "every value comes from the sidecar, the model's build stamp "
           "or commands.yaml -->")


def _manifest() -> dict:
    """`{name: entry}` from the command manifest, or `{}` when unreadable."""
    try:
        import yaml
    except ImportError:                                      # pragma: no cover
        return {}
    here = Path(__file__).resolve().parent
    for cand in (here / "skill" / "commands.yaml",
                 here.parents[1] / ".claude" / "skills" / "pdfdrill" / "commands.yaml"):
        try:
            data = yaml.safe_load(cand.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        return {c["name"]: c for c in (data.get("commands") or []) if c.get("name")}
    return {}


def _q(v) -> str:
    """A YAML scalar that survives a colon, a hash or a leading digit."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    if s == "" or any(c in s for c in ':#[]{},&*?|>%@`"\'\n') or s[:1].isdigit():
        return json.dumps(s, ensure_ascii=False)
    return s


def _seq(key: str, v) -> str:
    """A YAML sequence, not a Python repr. The model stores `authors` as a
    list and stringifying it wrote `authors: "[\'David I. Spivak\']"` — valid
    YAML for a STRING that happens to look like a list, which is the kind of
    value a reader has to un-guess."""
    if not v:
        return f"{key}: []"
    if isinstance(v, str):
        v = [v]
    return f"{key}: [%s]" % ", ".join(_q(x) for x in v)


def collect(pdf: Path) -> dict:
    """Everything the README states, as data. The only reader of the sidecar."""
    from .sidecar import Sidecar

    pdf = Path(pdf)
    sc = Sidecar(pdf)
    ev = dict(sc.evidence or {})
    info = dict(sc.pdfinfo or {})
    man = _manifest()

    # The sidecar exposes facts/evidence/pdfinfo as properties; the transition
    # log and the version are only in the file, so it is read once, here.
    try:
        raw = json.loads(sc.json_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        raw = {}
    trans = list(raw.get("transitions") or [])

    ran = []
    seen = set()
    for t in trans:
        n = t.get("node")
        if n and n not in seen:
            seen.add(n)
            ran.append(n)

    paid = sorted(n for n in seen if (man.get(n) or {}).get("network"))
    # A command is "not run" only if the manifest knows it and it never fired.
    offline = sorted(n for n, c in man.items()
                     if n not in seen and not c.get("network")
                     and c.get("section", "").startswith(("Build", "Introspection")))

    stamp, model_meta = {}, {}
    mp = sc.blob_dir / "model.docmodel.json"
    if mp.exists():
        try:
            model_meta = json.loads(mp.read_text(encoding="utf-8")).get("meta") or {}
            stamp = dict(model_meta.get("written") or {})
        except (OSError, ValueError):
            pass

    files = []
    try:
        for f in sorted(sc.blob_dir.iterdir()):
            if f.is_file():
                files.append((f.name, f.stat().st_size))
    except OSError:
        pass

    return {
        "bibkey": ev.get("bibkey") or pdf.stem,
        # pdfinfo's title is empty for most TeX output; the model carries the
        # one taken from the source (`\title{...}`) or from the OCR.
        "title": info.get("title") or ev.get("title") or model_meta.get("title"),
        "authors": model_meta.get("authors"),
        "pdf": pdf.name,
        "folder": str(sc.blob_dir),
        "source": {k: ev.get(k) for k in ("source_kind", "source_arxiv_id",
                                          "source_url") if ev.get(k)},
        "document": {
            "pages": ev.get("pages") or ev.get("page_count_text"),
            "bytes": ev.get("bytes"),
            "page_size": ev.get("page_size"),
            "producer": ev.get("producer"),
            "creator": ev.get("creator"),
        },
        "model": {
            "source": ev.get("model_source"),
            "objects": ev.get("model_object_counts") or {},
            "equations_with_cdn": ev.get("model_equations_with_cdn"),
        },
        "built_with": {
            "pdfdrill": raw.get("pdfdrill_version"),
            "commit": stamp.get("sha"),
            "dirty": stamp.get("dirty"),
        },
        "facts": sorted(sc.facts),
        "ran": ran,
        "paid": paid,
        # NOT TRUNCATED. `offline[:40]` cut the list alphabetically, so `model`
        # — the step whose absence matters most — fell off the end while
        # `abstract` and `annotate` stayed. A list that drops the important
        # entry to stay short is worse than a long one.
        "not_run": offline,
        "transitions": trans,
        "files": files,
    }


def render(d: dict) -> str:
    """The README itself: YAML front matter, then Markdown."""
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    y = ["---",
         f"bibkey: {_q(d['bibkey'])}",
         f"title: {_q(d['title'])}",
         f"pdf: {_q(d['pdf'])}",
         _seq("authors", d.get("authors")),
         f"generated: {now}"]
    for block in ("source", "document", "model", "built_with"):
        vals = {k: v for k, v in (d[block] or {}).items() if v not in (None, {}, "")}
        if not vals:
            continue
        y.append(f"{block}:")
        for k, v in vals.items():
            if isinstance(v, dict):
                y.append(f"  {k}:")
                y += [f"    {kk}: {_q(vv)}" for kk, vv in sorted(v.items())]
            else:
                y.append(f"  {k}: {_q(v)}")
    y.append("paid_steps: [%s]" % ", ".join(d["paid"]) if d["paid"]
             else "paid_steps: []            # nothing in this folder cost money")
    y.append("facts: [%s]" % ", ".join(d["facts"]))
    y.append("---")

    m = [_HEADER, "", f"# {d['title'] or d['bibkey']}", ""]
    if d["source"]:
        m.append("**Source** — " + ", ".join(f"{k.replace('source_', '')}: `{v}`"
                                             for k, v in d["source"].items()))
    doc = d["document"]
    if doc.get("pages"):
        m.append("**Document** — %s pages, %s, produced by %s."
                 % (doc.get("pages"), doc.get("page_size") or "size unknown",
                    doc.get("producer") or "an unnamed producer"))
    mo = d["model"]
    if mo.get("source"):
        counts = ", ".join(f"{v} {k}" for k, v in sorted(
            (mo.get("objects") or {}).items(), key=lambda kv: -kv[1])[:6])
        m.append(f"**Model** — built from `{mo['source']}`" +
                 (f": {counts}." if counts else "."))
    m.append("")

    m += ["## What was paid for", ""]
    if d["paid"]:
        m.append("These steps cost money or left the machine. The artefacts "
                 "they produced **cannot be rebuilt for free**:")
        m.append("")
        m += [f"- `{n}`" for n in d["paid"]]
    else:
        m.append("Nothing. Every artefact here was produced offline, with no "
                 "key and no network, and can be rebuilt from the PDF.")
    m.append("")

    m += ["## Process", "",
          "Every step this document has been through, in the order it "
          "happened, as the sidecar recorded it.", "",
          "| when | step | result | ms |", "|---|---|---|---|"]
    for t in d["transitions"]:
        m.append("| %s | `%s` | %s | %s |" % (
            t.get("ts", ""), t.get("node", ""),
            str(t.get("detail") or t.get("to") or "").replace("|", "\\|")[:90],
            round(t.get("cost_ms") or 0)))
    if not d["transitions"]:
        m.append("| — | — | nothing recorded | — |")
    m.append("")

    m += ["## Not run", "",
          "Absent is not false: these are steps that have **not been "
          "attempted**, not steps that found nothing.", "",
          ", ".join(f"`{n}`" for n in d["not_run"]) or "_(none)_", ""]

    m += ["## Files", "", "| file | bytes |", "|---|---|"]
    m += ["| `%s` | %s |" % (n, s) for n, s in d["files"]]
    m.append("")
    return "\n".join(y) + "\n\n" + "\n".join(m)


def write(pdf: Path) -> tuple[Path, dict]:
    """Write `README.md` into the document's folder. Returns (path, data)."""
    d = collect(pdf)
    out = Path(d["folder"]) / "README.md"
    out.write_text(render(d), encoding="utf-8")
    return out, d
