#!/usr/bin/env python3
"""Generate report.tex from a <bibkey>.tiddlers.json — the LaTeX analog of
formula-report.html.

    python3 tools/make_report_tex.py <tiddlers.json> [--out report.tex]

One longtable row per math object: the full tiddler identifier, the LaTeX
source as escaped text, the rendered math, and the page of first occurrence.
Sections: inline formulas (FO/FOX), display equations (EQ, with equation
number), tables (TAB). A formula tiddler carries no page field, so first
occurrence is derived from the first page-bearing tiddler (document order)
whose text transcludes it. Stdlib only; compile with xelatex.
"""
import argparse
import json
import re
from pathlib import Path

_ESC = {"\\": r"\textbackslash{}", "{": r"\{", "}": r"\}", "$": r"\$",
        "&": r"\&", "#": r"\#", "_": r"\_", "%": r"\%",
        "^": r"\textasciicircum{}", "~": r"\textasciitilde{}"}


def esc_text(s: str) -> str:
    out = "".join(_ESC.get(c, c) for c in s)
    # break opportunities in long token runs (the column must wrap)
    return out.replace(r"\textbackslash{}", r"\textbackslash{}\allowbreak{}")


def first_pages(tiddlers: list[dict], bibkey: str) -> dict[str, str]:
    """title -> page of the first transcluding page-bearing tiddler."""
    pat = re.compile(r"\{\{(" + re.escape(bibkey) + r"_(?:FOX?_?\w+))\|\|")
    first: dict[str, str] = {}
    for t in tiddlers:
        page, text = t.get("page"), t.get("text", "")
        if not page or "{{" not in text:
            continue
        for m in pat.finditer(text):
            first.setdefault(m.group(1), page)
    return first


def rows_for(tiddlers, bibkey):
    fo, eq, tab, dia = [], [], [], []
    fpage = first_pages(tiddlers, bibkey)
    for t in tiddlers:
        title = t.get("title", "")
        m = re.match(re.escape(bibkey) + r"_(FOX?|EQ|TAB|DIA|PIC)", title)
        if not m:
            continue
        kind = m.group(1)
        latex = t.get("latex") or t.get("latex_code") or ""
        page = t.get("page") or fpage.get(title, "")
        dims = t.get("width", ""), t.get("height", "")
        if kind in ("FO", "FOX"):
            fo.append((title, latex, page))
        elif kind == "EQ":
            eq.append((title, latex, page, t.get("equation_number", ""),
                       t.get("width", "")))
        elif kind == "TAB":
            tab.append((title, latex, page, dims))
        else:
            dia.append((title, latex, page, dims))
    return fo, eq, tab, dia


def texzip_images(texzip_dir: Path):
    """Map (page:int, height, width) and page -> image path from a MathPix
    tex.zip expansion (images named <id>-<page>_<h>_<w>_<y>_<x>.jpg)."""
    by_key, by_page = {}, {}
    for img in sorted(texzip_dir.rglob("*.jpg")) +                sorted(texzip_dir.rglob("*.png")):
        m = re.search(r"-(\d+)_(\d+)_(\d+)_\d+_\d+\.\w+$", img.name)
        if not m:
            continue
        page, h, w = (int(x) for x in m.groups())
        by_key[(page, h, w)] = img
        by_page.setdefault(page, img)
    return by_key, by_page


def jpg_width(path: Path):
    """Actual pixel width of the (possibly trimmed) crop; None without PIL."""
    try:
        from PIL import Image
        with Image.open(path) as im:
            return im.size[0]
    except Exception:
        return None


def crop_cell(crops_dir: Path | None, out_dir: Path, title: str,
              px_width="", px2mm=None, col_mm=None) -> str:
    """An \\includegraphics cell for the tiddler's downloaded CDN crop.

    With px2mm (mm per MathPix page pixel) and the region's pixel width the
    crop is set at its EXACT original physical size, capped at the column
    width; otherwise it fills the column.
    """
    if not crops_dir:
        return "---"
    img = crops_dir / f"{title}.jpg"
    if not img.is_file() or img.stat().st_size < 500:
        return "---"
    try:
        rel = img.relative_to(out_dir)
    except ValueError:
        rel = img
    size = "width=\\linewidth"
    if px2mm:
        try:
            real = jpg_width(img)
            w_mm = float(real if real else px_width) * px2mm
            if col_mm and w_mm > col_mm:
                w_mm = col_mm
            size = "width=%.1fmm" % w_mm
        except (TypeError, ValueError):
            pass
    return ("\\includegraphics[%s]{%s}"
            % (size, str(rel).replace("\\", "/")))


PAPER_MM = {"a4": (210, 297), "a3": (297, 420)}

PREAMBLE = r"""%% report.tex — generated by tools/make_report_tex.py; compile with xelatex
\documentclass[10pt]{article}
\usepackage[%(geom)s,margin=18mm]{geometry}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{longtable}
\usepackage{array}
\usepackage{graphicx}
\setlength{\parindent}{0pt}
\newcommand{\ident}[1]{\texttt{\small #1}}
\begin{document}
"""


def col_widths(usable_mm: float, with_image: bool):
    """(ident, page, src, rendered[, image]) widths in mm for the usable span.
    ~12mm of the span is left for inter-column rules/padding."""
    span = usable_mm - 12
    ident, page = 20, 7
    rest = span - ident - page
    if with_image:
        src = round(rest * 0.29)
        rend = round(rest * 0.31)
        return ident, page, src, rend, rest - src - rend
    src = round(rest / 2)
    return ident, page, src, rest - src


def table_open(caption: str, widths) -> str:
    cols = "|" + "|".join("p{%smm}" % w for w in widths) + "|"
    heads = {4: ("Identifier", "Page", "LaTeX source", "Rendered"),
             5: ("Identifier", "Page", "LaTeX source", "Rendered",
                 "Scan image")}[len(widths)]
    return (
        "\\section*{%s}\n" % caption +
        "\\begin{longtable}{%s}\n\\hline\n" % cols +
        " & ".join("\\textbf{%s}" % h for h in heads) +
        " \\\\\n\\hline\\endhead\n")


def renderable(latex: str) -> str:
    """Return latex safe to put inside $...$, or "" when it is not.

    One malformed snippet (bh2_EQ0147 carried a stray \\end{itemize}) hung
    xelatex for 10 minutes inside a longtable cell — every snippet is
    validated here and demoted to source-only when it cannot render.
    """
    lx = re.sub(r"\s+", " ", latex).strip()
    # display delimiters: strip a leading \[ / trailing \]; reject mid-string
    lx = re.sub(r"^\\\[\s*", "", lx)
    lx = re.sub(r"\s*\\\]$", "", lx)
    if r"\[" in lx or r"\]" in lx or "$" in lx:
        return ""
    if re.sub(r"\\%", "", lx).count("%"):
        return ""
    # brace balance, with \\ and escaped \{ \} removed first
    stripped = re.sub(r"\\[{}]", "", lx.replace("\\\\", ""))
    depth = 0
    for c in stripped:
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth < 0:
                return ""
    if depth != 0:
        return ""
    if len(re.findall(r"\\left(?![a-zA-Z])", lx)) != \
       len(re.findall(r"\\right(?![a-zA-Z])", lx)):
        return ""
    if sorted(re.findall(r"\\begin\{(\w+\*?)\}", lx)) != \
       sorted(re.findall(r"\\end\{(\w+\*?)\}", lx)):
        return ""
    return lx


def row(title, latex, page, extra="", image=None) -> str:
    ident = "\\ident{%s}%s" % (esc_text(title),
                               (" %s" % esc_text(extra)) if extra else "")
    src = "{\\ttfamily\\footnotesize %s}" % esc_text(latex) if latex else "---"
    safe = renderable(latex) if latex else ""
    math = ("$\\displaystyle %s$" % safe) if safe \
        else ("\\emph{(not rendered)}" if latex else "---")
    if image is not None:
        return "%s & %s & %s & %s & %s \\\\ \\hline\n" % (
            ident, esc_text(str(page)), src, math, image)
    return "%s & %s & %s & %s \\\\ \\hline\n" % (
        ident, esc_text(str(page)), src, math)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tiddlers")
    ap.add_argument("--out", default=None)
    ap.add_argument("--crops", default=None,
                    help="directory of downloaded CDN crops (<title>.jpg); "
                         "adds a Scan-image column to equations and tables")
    ap.add_argument("--paper", choices=("a4", "a3"), default="a4")
    ap.add_argument("--landscape", action="store_true")
    ap.add_argument("--texzip", default=None,
                    help="expanded MathPix tex.zip directory; its images/ "
                         "(the regions MathPix could NOT OCR) fill the "
                         "'Unrecovered image regions' section locally, "
                         "no CDN download")
    ap.add_argument("--px2mm", type=float, default=None,
                    help="mm per MathPix page pixel: pdf_page_width_pt * "
                         "0.3528 / lines.json page_width_px. Sets each scan "
                         "image at its EXACT original physical size "
                         "(capped at the column width).")
    args = ap.parse_args()
    path = Path(args.tiddlers)
    tiddlers = json.loads(path.read_text())
    bibkey = path.name.replace(".tiddlers.json", "")
    fo, eq, tab, dia = rows_for(tiddlers, bibkey)
    dest = Path(args.out) if args.out else path.parent / "report.tex"
    crops = Path(args.crops).resolve() if args.crops else None
    out_dir = dest.resolve().parent

    w_mm, h_mm = PAPER_MM[args.paper]
    if args.landscape:
        w_mm, h_mm = h_mm, w_mm
    usable = w_mm - 36  # 18mm margins
    geom = "%spaper%s" % (args.paper, ",landscape" if args.landscape else "")
    eq_widths = col_widths(usable, with_image=bool(crops))
    fo_widths = col_widths(usable, with_image=False)
    img_col = eq_widths[4] if crops else None
    if crops and args.px2mm:
        # the widest actual crop decides the image column; freed mm -> Rendered
        widest = 0.0
        for title, _lx, _pg, _num, wpx in eq:
            f = crops / f"{title}.jpg"
            if f.is_file():
                w = jpg_width(f) or (float(wpx) if wpx else 0)
                widest = max(widest, float(w) * args.px2mm)
        if widest and widest + 2 < eq_widths[4]:
            freed = eq_widths[4] - (round(widest) + 2)
            eq_widths = (eq_widths[0], eq_widths[1], eq_widths[2],
                         eq_widths[3] + freed, round(widest) + 2)
            img_col = eq_widths[4]

    out = [PREAMBLE % {"geom": geom}]
    out.append("\\section*{%s — formula report}\n"
               "%d inline formulas, %d display equations, %d tables, "
               "%d unrecovered image regions.\n"
               % (esc_text(bibkey), len(fo), len(eq), len(tab), len(dia)))
    out.append(table_open("Display equations", eq_widths))
    for title, latex, page, num, wpx in eq:
        img = crop_cell(crops, out_dir, title, px_width=wpx,
                        px2mm=args.px2mm, col_mm=img_col) if crops else None
        out.append(row(title, latex, page, extra=num, image=img))
    out.append("\\end{longtable}\n")

    out.append(table_open("Inline formulas (first occurrence)", fo_widths))
    for title, latex, page in fo:
        out.append(row(title, latex, page))
    out.append("\\end{longtable}\n")

    if tab:
        ti, ts, tim, tp = col_widths(usable, with_image=True)[0], None, None, 9
        span = usable - 12 - 26 - 9
        ts = round(span * 0.5)
        tim = span - ts
        out.append("\\section*{Tables}\n\\begin{longtable}"
                   "{|p{26mm}|p{9mm}|p{%smm}|p{%smm}|}\n\\hline\n"
                   % (ts, tim) +
                   "\\textbf{Identifier} & \\textbf{Page} & "
                   "\\textbf{Content (LaTeX source if any)} & "
                   "\\textbf{Scan image} \\\\\n\\hline\\endhead\n")
        for title, latex, page, dims in tab:
            body = ("{\\ttfamily\\footnotesize %s}" % esc_text(latex)
                    ) if latex else ("(no LaTeX source; %s\\,$\\times$\\,%s px"
                                     " region — see tables.html)" % dims)
            img = crop_cell(crops, out_dir, title,
                            px_width=dims[0], px2mm=args.px2mm, col_mm=tim)
            out.append("\\ident{%s} & %s & %s & %s \\\\ \\hline\n"
                       % (esc_text(title), esc_text(str(page)), body, img))
        out.append("\\end{longtable}\n")

    if dia:
        zkey, zpage = ({}, {})
        if args.texzip:
            zkey, zpage = texzip_images(Path(args.texzip))
        span = usable - 12 - 20 - 7
        dimg = round(span * 0.55)
        dnote = span - dimg
        out.append(
            "\\section*{Unrecovered image regions — TikZ / table / "
            "failed-math candidates}\n"
            "Regions MathPix left as images (no LaTeX). Reconstruct with "
            "\\texttt{pdfdrill vision} (LLM classify + transcribe to "
            "TikZ/tabular/math); verify an LLM result against the real ink "
            "with inkdrill.\n"
            "\\begin{longtable}{|p{20mm}|p{7mm}|p{%smm}|p{%smm}|}\n"
            "\\hline\n\\textbf{Identifier} & \\textbf{Page} & "
            "\\textbf{Image} & \\textbf{Source} \\\\\n"
            "\\hline\\endhead\n" % (dimg, dnote))
        for title, latex, page, dims in dia:
            img_path = None
            try:
                key = (int(page), int(dims[1]), int(dims[0]))
                img_path = zkey.get(key) or zpage.get(int(page))
            except (TypeError, ValueError):
                pass
            if img_path is None and crops:
                cand = crops / f"{title}.jpg"
                img_path = cand if cand.is_file() else None
            if img_path is not None:
                w_mm = None
                if args.px2mm:
                    real = jpg_width(img_path) or dims[0]
                    try:
                        w_mm = min(float(real) * args.px2mm, dimg)
                    except (TypeError, ValueError):
                        pass
                size = ("width=%.1fmm" % w_mm) if w_mm else                     "width=\\linewidth"
                try:
                    rel = img_path.resolve().relative_to(out_dir)
                except ValueError:
                    rel = img_path
                cell = "\\includegraphics[%s]{%s}" % (
                    size, str(rel).replace("\\", "/"))
                srcnote = "tex.zip (local)" if zkey or zpage else "crops"
            else:
                cell = "\\emph{(image not on disk — pass --texzip or "
                cell += "download the CDN crop)}"
                srcnote = "CDN only"
            out.append("\\ident{%s} & %s & %s & %s \\\\ \\hline\n"
                       % (esc_text(title), esc_text(str(page)), cell,
                          srcnote))
        out.append("\\end{longtable}\n")

    out.append("\\end{document}\n")
    dest.write_text("".join(out))
    print(f"{dest}: {len(eq)} equations, {len(fo)} formulas, "
          f"{len(tab)} tables, {dest.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
