#!/usr/bin/env python3
"""Generate report.tex from a <bibkey>.tiddlers.json — the LaTeX analog of
formula-report.html.

    python3 tools/make_report_tex.py <tiddlers.json> [--out report.tex]

One longtable row per math object: the full tiddler identifier, the LaTeX
source as escaped text, the rendered math, and the page of first occurrence.
Sections: inline formulas (FO/FOX), display equations (EQ, with equation
number), tables (TAB). A formula tiddler carries no page field, so first
occurrence is derived from the first page-bearing tiddler (document order)
whose text transcludes it. Stdlib only; compile with xelatex.
"""
import argparse
import json
import re
from pathlib import Path

_ESC = {"\\": r"\textbackslash{}", "{": r"\{", "}": r"\}", "$": r"\$",
        "&": r"\&", "#": r"\#", "_": r"\_", "%": r"\%",
        "^": r"\textasciicircum{}", "~": r"\textasciitilde{}"}


def esc_text(s: str) -> str:
    out = "".join(_ESC.get(c, c) for c in s)
    # break opportunities in long token runs (the column must wrap)
    return out.replace(r"\textbackslash{}", r"\textbackslash{}\allowbreak{}")


def first_pages(tiddlers: list[dict], bibkey: str) -> dict[str, str]:
    """title -> page of the first transcluding page-bearing tiddler."""
    pat = re.compile(r"\{\{(" + re.escape(bibkey) + r"_(?:FOX?_?\w+))\|\|")
    first: dict[str, str] = {}
    for t in tiddlers:
        page, text = t.get("page"), t.get("text", "")
        if not page or "{{" not in text:
            continue
        for m in pat.finditer(text):
            first.setdefault(m.group(1), page)
    return first


def rows_for(tiddlers, bibkey):
    fo, eq, tab = [], [], []
    fpage = first_pages(tiddlers, bibkey)
    for t in tiddlers:
        title = t.get("title", "")
        m = re.match(re.escape(bibkey) + r"_(FOX?|EQ|TAB)", title)
        if not m:
            continue
        kind = m.group(1)
        latex = t.get("latex") or t.get("latex_code") or ""
        page = t.get("page") or fpage.get(title, "")
        if kind in ("FO", "FOX"):
            fo.append((title, latex, page))
        elif kind == "EQ":
            eq.append((title, latex, page, t.get("equation_number", "")))
        else:
            dims = t.get("width", ""), t.get("height", "")
            tab.append((title, latex, page, dims))
    return fo, eq, tab


def crop_cell(crops_dir: Path | None, out_dir: Path, title: str) -> str:
    """An \\includegraphics cell for the tiddler's downloaded CDN crop."""
    if not crops_dir:
        return "---"
    img = crops_dir / f"{title}.jpg"
    if not img.is_file() or img.stat().st_size < 500:
        return "---"
    try:
        rel = img.relative_to(out_dir)
    except ValueError:
        rel = img
    return ("\\includegraphics[width=\\linewidth]{%s}"
            % str(rel).replace("\\", "/"))


PREAMBLE = r"""% report.tex — generated by tools/make_report_tex.py; compile with xelatex
\documentclass[10pt]{article}
\usepackage[a4paper,margin=18mm]{geometry}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{longtable}
\usepackage{array}
\usepackage{graphicx}
\setlength{\parindent}{0pt}
\newcommand{\ident}[1]{\texttt{\small #1}}
\begin{document}
"""


def table_open(caption: str, with_image: bool = False) -> str:
    if with_image:
        return (
            "\\section*{%s}\n" % caption +
            "\\begin{longtable}{|p{24mm}|p{40mm}|p{40mm}|p{46mm}|p{8mm}|}\n"
            "\\hline\n\\textbf{Identifier} & \\textbf{LaTeX source} & "
            "\\textbf{Rendered} & \\textbf{Scan image} & "
            "\\textbf{Page} \\\\\n\\hline\\endhead\n")
    return (
        "\\section*{%s}\n" % caption +
        "\\begin{longtable}{|p{32mm}|p{60mm}|p{60mm}|p{10mm}|}\n"
        "\\hline\n\\textbf{Identifier} & \\textbf{LaTeX source} & "
        "\\textbf{Rendered} & \\textbf{Page} \\\\\n\\hline\\endhead\n")


def renderable(latex: str) -> str:
    """Return latex safe to put inside $...$, or "" when it is not.

    One malformed snippet (bh2_EQ0147 carried a stray \\end{itemize}) hung
    xelatex for 10 minutes inside a longtable cell — every snippet is
    validated here and demoted to source-only when it cannot render.
    """
    lx = re.sub(r"\s+", " ", latex).strip()
    # display delimiters: strip a leading \[ / trailing \]; reject mid-string
    lx = re.sub(r"^\\\[\s*", "", lx)
    lx = re.sub(r"\s*\\\]$", "", lx)
    if r"\[" in lx or r"\]" in lx or "$" in lx:
        return ""
    if re.sub(r"\\%", "", lx).count("%"):
        return ""
    # brace balance, with \\ and escaped \{ \} removed first
    stripped = re.sub(r"\\[{}]", "", lx.replace("\\\\", ""))
    depth = 0
    for c in stripped:
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth < 0:
                return ""
    if depth != 0:
        return ""
    if len(re.findall(r"\\left(?![a-zA-Z])", lx)) != \
       len(re.findall(r"\\right(?![a-zA-Z])", lx)):
        return ""
    if sorted(re.findall(r"\\begin\{(\w+\*?)\}", lx)) != \
       sorted(re.findall(r"\\end\{(\w+\*?)\}", lx)):
        return ""
    return lx


def row(title, latex, page, extra="", image=None) -> str:
    ident = "\\ident{%s}%s" % (esc_text(title),
                               (" %s" % esc_text(extra)) if extra else "")
    src = "{\\ttfamily\\footnotesize %s}" % esc_text(latex) if latex else "---"
    safe = renderable(latex) if latex else ""
    math = ("$\\displaystyle %s$" % safe) if safe \
        else ("\\emph{(not rendered)}" if latex else "---")
    if image is not None:
        return "%s & %s & %s & %s & %s \\\\ \\hline\n" % (
            ident, src, math, image, esc_text(str(page)))
    return "%s & %s & %s & %s \\\\ \\hline\n" % (ident, src, math, esc_text(str(page)))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tiddlers")
    ap.add_argument("--out", default=None)
    ap.add_argument("--crops", default=None,
                    help="directory of downloaded CDN crops (<title>.jpg); "
                         "adds a Scan-image column to equations and tables")
    args = ap.parse_args()
    path = Path(args.tiddlers)
    tiddlers = json.loads(path.read_text())
    bibkey = path.name.replace(".tiddlers.json", "")
    fo, eq, tab = rows_for(tiddlers, bibkey)
    dest = Path(args.out) if args.out else path.parent / "report.tex"
    crops = Path(args.crops).resolve() if args.crops else None
    out_dir = dest.resolve().parent

    out = [PREAMBLE]
    out.append("\\section*{%s — formula report}\n"
               "%d inline formulas, %d display equations, %d tables.\n"
               % (esc_text(bibkey), len(fo), len(eq), len(tab)))
    out.append(table_open("Display equations", with_image=bool(crops)))
    for title, latex, page, num in eq:
        img = crop_cell(crops, out_dir, title) if crops else None
        out.append(row(title, latex, page, extra=num, image=img))
    out.append("\\end{longtable}\n")

    out.append(table_open("Inline formulas (first occurrence)"))
    for title, latex, page in fo:
        out.append(row(title, latex, page))
    out.append("\\end{longtable}\n")

    if tab:
        out.append("\\section*{Tables}\n\\begin{longtable}"
                   "{|p{28mm}|p{62mm}|p{62mm}|p{8mm}|}\n\\hline\n"
                   "\\textbf{Identifier} & \\textbf{Content (LaTeX source"
                   " if any)} & \\textbf{Scan image} & "
                   "\\textbf{Page} \\\\\n\\hline\\endhead\n")
        for title, latex, page, dims in tab:
            body = ("{\\ttfamily\\footnotesize %s}" % esc_text(latex)
                    ) if latex else ("(no LaTeX source; %s\\,$\\times$\\,%s px"
                                     " region — see tables.html)" % dims)
            img = crop_cell(crops, out_dir, title)
            out.append("\\ident{%s} & %s & %s & %s \\\\ \\hline\n"
                       % (esc_text(title), body, img, esc_text(str(page))))
        out.append("\\end{longtable}\n")

    out.append("\\end{document}\n")
    dest.write_text("".join(out))
    print(f"{dest}: {len(eq)} equations, {len(fo)} formulas, "
          f"{len(tab)} tables, {dest.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
