#!/usr/bin/env python3
"""skillsync — keep pdfdrill's command surface coherent from ONE source of truth.

The single source of truth is `.claude/skills/pdfdrill/commands.yaml`. From it:
  * check         validate the manifest against cli.py's HANDLERS dict (the only
                  ground truth for which commands exist) — the CI drift gate.
  * render-help   emit the `--help` body to `src/pdfdrill/_help_generated.txt`
                  (consumed by cli._print_help) — no more hand-maintained string.
  * render-skill  regenerate the command tables inside SKILL.md, between the
                  <!-- COMMANDS:BEGIN/END --> markers, preserving authored prose.
  * bundle        copy the canonical SKILL folder into src/pdfdrill/skill/ so the
                  wheel is self-contained (`pdfdrill skill --emit/--json` work
                  from an installed wheel with no repo).
  * all           check + render-help + render-skill + bundle.

Claude (Claude Code CLI or claude.ai) runs this after editing the manifest,
before committing. The external drillui TUI never runs it — it just reads the
manifest. Repo-agnostic; pyyaml is the only dependency.
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

import yaml

BEGIN = "<!-- COMMANDS:BEGIN (generated by skillsync — do not edit by hand) -->"
END = "<!-- COMMANDS:END -->"


def _skill_dir(repo: Path) -> Path:
    return repo / ".claude/skills/pdfdrill"


def load_manifest(repo: Path) -> dict:
    return yaml.safe_load((_skill_dir(repo) / "commands.yaml").read_text())


def handler_names(repo: Path) -> list[str]:
    """The ground truth: the module-level HANDLERS dict in cli.py."""
    cli = (repo / "src/pdfdrill/cli.py").read_text()
    block = re.search(r"HANDLERS\s*=\s*\{(.*?)\n    \}", cli, re.S).group(1)
    return [m.group(1) for m in re.finditer(r'"(\w+)":', block)]


def usage_string(cmd: dict) -> str:
    parts = [f"<{p['name']}>" for p in cmd.get("positionals", [])]
    for f in cmd.get("flags", []):
        token = f["flag"]
        if f.get("type") == "flag":
            parts.append(f"[{token}]")
        else:
            ph = (f.get("choices") and "|".join(f["choices"])) or f.get("name", "X").upper()
            parts.append(f"[{token} {ph}]")
    return " ".join(parts)


# --------------------------------------------------------------------------- #
def cmd_check(repo: Path) -> int:
    man = load_manifest(repo)
    man_names = [c["name"] for c in man["commands"]]
    hset, mset = set(handler_names(repo)), set(man_names)
    issues = 0
    missing = sorted(hset - mset)
    extra = sorted(mset - hset)
    untyped = [c["name"] for c in man["commands"] if not c.get("typed")]
    dupes = sorted({n for n in man_names if man_names.count(n) > 1})

    print(f"handlers (truth): {len(hset)}   manifest: {len(mset)}")
    if missing:
        issues += 1; print(f"✗ in cli.py HANDLERS but MISSING from manifest: {missing}")
    if extra:
        issues += 1; print(f"✗ in manifest but NOT a handler (stale): {extra}")
    if dupes:
        issues += 1; print(f"✗ duplicate manifest entries: {dupes}")
    if not issues:
        print("✓ manifest ↔ HANDLERS: in sync")
    if untyped:
        print(f"⚠ {len(untyped)} command(s) still need typed flags (typed:false): "
              f"{untyped[:8]}{'…' if len(untyped) > 8 else ''}")
    return 1 if issues else 0


def render_help_text(man: dict) -> str:
    lines = []
    intro = man.get("help_intro", "").rstrip()
    if intro:
        lines += [intro, ""]
    else:
        lines += ["pdfdrill — portable PDF drill-down toolkit", ""]
    by_section: dict[str, list[dict]] = {}
    for c in man["commands"]:
        by_section.setdefault(c["section"], []).append(c)
    for section, cmds in by_section.items():
        lines.append(f"{section}:")
        for c in cmds:
            left = f"  pdfdrill {c['name']} {usage_string(c)}".rstrip()
            pad = " " if len(left) >= 46 else ""
            lines.append(f"{left:<46}{pad}{c['summary']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def cmd_render_help(repo: Path) -> int:
    man = load_manifest(repo)
    out = repo / "src/pdfdrill/_help_generated.txt"
    out.write_text(render_help_text(man))
    print(f"wrote {out}  ({len(man['commands'])} commands)")
    return 0


def render_tables(man: dict) -> str:
    by_section: dict[str, list[dict]] = {}
    for c in man["commands"]:
        by_section.setdefault(c["section"], []).append(c)
    out = [BEGIN, "", "## Command reference", "",
           "_Generated from `commands.yaml` by skillsync. Edit the manifest, not this section._", ""]
    for section, cmds in by_section.items():
        out += [f"### {section}", "", "| Command | Returns |", "|---|---|"]
        for c in cmds:
            sig = f"`pdfdrill {c['name']} {usage_string(c)}`".rstrip("` ") + "`"
            summary = c["summary"].replace("|", "\\|")
            tag = " _(network)_" if c.get("network") else ""
            out.append(f"| {sig} | {summary}{tag} |")
        out.append("")
    out.append(END)
    return "\n".join(out)


def cmd_render_skill(repo: Path) -> int:
    man = load_manifest(repo)
    skill = _skill_dir(repo) / "SKILL.md"
    text = skill.read_text()
    region = render_tables(man)
    if BEGIN in text and END in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), region, text, flags=re.S)
    else:
        text = text.rstrip() + "\n\n" + region + "\n"
    # The preflight ATTESTATION TOKEN must be the LAST line: a checksum of the whole
    # SKILL body, so an LLM that read to the end can prove it (the hard-stop gate).
    import sys as _sys
    _sys.path.insert(0, str((repo / "src").resolve()))
    from pdfdrill import preflight as _pf
    text = _pf.render_token_block(text)
    skill.write_text(text)
    print(f"synced {skill}  ({len(man['commands'])} commands + preflight token)")
    return 0


def cmd_bundle(repo: Path) -> int:
    src = _skill_dir(repo)
    dst = repo / "src/pdfdrill/skill"
    dst.mkdir(parents=True, exist_ok=True)
    n = 0
    for f in sorted(src.iterdir()):
        if f.is_file():
            shutil.copy2(f, dst / f.name)
            n += 1
    print(f"bundled {n} files {src} -> {dst}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="sync pdfdrill SKILL/help from commands.yaml")
    ap.add_argument("action", choices=["check", "render-help", "render-skill", "bundle", "all"])
    ap.add_argument("repo", nargs="?", default=".")
    a = ap.parse_args()
    repo = Path(a.repo)
    if a.action == "check":
        return cmd_check(repo)
    if a.action == "render-help":
        return cmd_render_help(repo)
    if a.action == "render-skill":
        return cmd_render_skill(repo)
    if a.action == "bundle":
        return cmd_bundle(repo)
    if a.action == "all":
        rc = cmd_check(repo)
        cmd_render_help(repo)
        cmd_render_skill(repo)
        cmd_bundle(repo)
        return rc
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
